services:
  - type: web
    name: opensign-api
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ""
      - key: PORT
        value: 10000
      - key: PARSE_SERVER_URL
        value: https://opensign-api.onrender.com
      - key: PARSE_PUBLIC_SERVER_URL
        value: https://opensign-api.onrender.com
      - key: APP_ID
        value: opensign
      - key: MASTER_KEY
        value: ""
      - key: PARSE_MOUNT
        value: /parse
      - key: ADMIN_PANEL_MASTER_KEY
        value: ""
      - key: JWT_SECRET
        value: ""
      - key: SMTP_HOST
        value: ""
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: ""
      - key: SMTP_PASSWORD
        value: ""
      - key: VOXBRIDGE_API_URL
        value: https://epic-sharing-maggot.ngrok-free.app
      - key: VOXBRIDGE_API_KEY
        value: ""

  - type: web
    name: opensign-dashboard
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run preview -- --host
    envVars:
      - key: VITE_PARSE_SERVER_URL
        value: https://opensign-api.onrender.com
      - key: VITE_APP_NAME
        value: OpenSign
      - key: VITE_API_URL
        value: https://opensign-api.onrender.com

databases:
  - name: opensign-db
    databaseName: opensign
    plan: free
